GET http://localhost:3000/posts HTTP/1.1
###
GET http://localhost:3000/api/posts/1 HTTP/1.1
###
POST http://localhost:3000/posts HTTP/1.1
content-type: application/json

{
      "title": "using rest client",
      "content": "Rest Client is easy...",
      "tags": [
        "rest",
        "client",
        "http",
        "crud"
      ],
      "imgURL": "https://www.betterup.com/hubfs/Blog%20Images/types-of-rest-blog-1.jpg",
      "authorId": 1
    }

###
PUT http://localhost:3000/posts/3 HTTP/1.1
content-type: application/json

{
      "id": 3,
      "title": "json-server",
      "content": "JSON is easy...",
      "tags": [
        "json-server",
        "rest",
        "api"
      ],
      "imgURL": "https://i.insider.com/61d1c0e2aa741500193b2d18?width=1136&format=jpeg",
      "authorId": 1
    }

###
PATCH http://localhost:3000/posts/1 HTTP/1.1
content-type: application/json

{
      "id": 2,
      "title": "json-server patch example"
}

###

DELETE http://localhost:3000/posts/4 HTTP/1.1