export const SUBMIT_TODO_START = "SUBMIT_TODO_START";
export type SUBMIT_TODO_START = typeof SUBMIT_TODO_START;

export const SUBMIT_TODO_SUCCEEDED = "SUBMIT_TODO_SUCCEEDED";
export type SUBMIT_TODO_SUCCEEDED = typeof SUBMIT_TODO_SUCCEEDED;

export const SUBMIT_TODO_FAILED = "SUBMIT_TODO_FAILED";
export type SUBMIT_TODO_FAILED = typeof SUBMIT_TODO_FAILED;

export const EDIT_TODO_START = "EDIT_TODO_START";
export type EDIT_TODO_START = typeof EDIT_TODO_START;

export const EDIT_TODO_SUCCEEDED = "EDIT_TODO_SUCCEEDED";
export type EDIT_TODO_SUCCEEDED = typeof EDIT_TODO_SUCCEEDED;

export const EDIT_TODO_FAILED = "EDIT_TODO_FAILED";
export type EDIT_TODO_FAILED = typeof EDIT_TODO_FAILED;

export const DELETE_TODO_START = "DELETE_TODO_START";
export type DELETE_TODO_START = typeof DELETE_TODO_START;

export const DELETE_TODO_SUCCEEDED = "DELETE_TODO_SUCCEEDED";
export type DELETE_TODO_SUCCEEDED = typeof DELETE_TODO_SUCCEEDED;

export const DELETE_TODO_FAILED = "DELETE_TODO_FAILED";
export type DELETE_TODO_FAILED = typeof DELETE_TODO_FAILED;

export const TODOS_FETCH_REQUESTED = "TODOS_FETCH_REQUESTED";
export type TODOS_FETCH_REQUESTED = typeof TODOS_FETCH_REQUESTED;

export const TODOS_FETCH_SUCCEEDED = "TODOS_FETCH_SUCCEEDED";
export type TODOS_FETCH_SUCCEEDED = typeof TODOS_FETCH_SUCCEEDED;

export const TODOS_FETCH_FAILED = "TODOS_FETCH_FAILED";
export type TODOS_FETCH_FAILED = typeof TODOS_FETCH_FAILED;


